[fzf]
version = "0.67.0"
installation = "external-sources"

[fzf.checksums] # publishes shas
darwin_arm64 = "b7f34c964d8e52c471c933cef8ec43dc71997c266cafafd1b013bed10fc229a1"
darwin_amd64 = "88dc853e0914793a2e7be0d1acfe6c922d9ccad08e3302df092399775b0279ff"
linux_amd64 = "4be08018ca37b32518c608741933ea335a406de3558242b60619e98f25be2be1"
linux_arm64 = "7071f48c2ac0f2bc992d6d33cc36fd675a579a98cc976dda699eea07dd5e9c58"
