# Configuration documentation: https://geminicli.com/docs/get-started/configuration/

[gemini]
model = "gemini-3-pro-preview"

[gemini.telemetry]
enabled = false
log_prompts = false

[gemini.ui]
show_line_numbers = true
show_memory_usage = true
show_model_info_in_chat = true

[gemini.ui.footer]
hide_context_percentage = false

[gemini.general]
enable_auto_update = false
preview_features = true
vim_mode = true

[gemini.extensions]

  [gemini.extensions.conductor]
  url = "https://github.com/gemini-cli-extensions/conductor"
  ref = "v0.2.0"
  enabled = true
