[mise]
version = "v2026.1.8"
installation = "external-sources"

[mise.checksums]
darwin_arm64 = "e0390b8f5f40cd020f26b12520ad8bcc0dbffddc330b216829b1b79e621d6717"
darwin_amd64 = "be5b6c08cbccafb422ccb420fbacc51489407879e6c73f122d3e69d2cef176bc"
linux_amd64 = "434effb5cd1cb8ac835a7ff59b98e3733b6588ea2d0f0f5f481fcdea51996e11"
linux_arm64 = "7c2d49920819d6131cad11c3ed89611d74c60f27c4af31d57a771bed28161a96"

[mise.settings]
disable_hints = ["self_update"]

[mise.global_tools]

  [mise.global_tools.node]
  version = "lts"
  enabled = true

  [mise.global_tools.python]
  version = "3.14"
  enabled = true

  [mise.global_tools.pnpm]
  version = "10.2.0"
  enabled = true

  [mise.global_tools.java]
  version = "temurin-21.0.5"
  enabled = true

  [mise.global_tools.rust]
  version = "1.83.0"
  enabled = true

  [mise.global_tools.uv]
  version = "0.9.27"
  enabled = true

  [mise.global_tools."npm:@google/gemini-cli"]
  version = "0.29.0"
  enabled = true
  postinstall = "install-gemini-extensions.sh"

  [mise.global_tools.bun]
  version = "1.3.6"
  enabled = true
