name: Update dependencies

on:
  schedule:
    # Run at 06:00 on the 1st and 15th of every month
    - cron: '0 6 1,15 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bazel-with-cache

      - name: Install Python tools
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y python3-dev

      - name: Update Python dependencies
        run: ./tools/update_deps.sh --python-only

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there are changes
          if git diff --quiet; then
            echo "No changes detected."
            exit 0
          fi

          # Config git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create branch
          BRANCH_NAME="deps/python"
          git checkout -b "$BRANCH_NAME"

          # Commit changes
          git add .
          git commit -m "chore(python): update python dependencies"

          # Push branch
          git push -f origin "$BRANCH_NAME"

          # Create PR if not exists
          if ! gh pr view "$BRANCH_NAME"; then
            gh pr create \
              --title "chore(python): update python dependencies" \
              --body "Updates Python dependencies (\`requirements.lock.txt\`). This PR was automatically generated by the \`update-deps\` workflow." \
              --base main \
              --head "$BRANCH_NAME"
          else
            echo "Pull request already exists."
          fi
